name: "ll_project"
type: "python:3.10"

relationships:
  database: "db:postgresql"

#Configuration when app is exposed to the web
web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      expires: 1h
      allow: true

#Size of the persistent disk of application in MB
disk: 512

#Local read/write mount for logs
mounts:
  "logs":
    source: local
    source_path: logs

#Hooks excuted during the lifecycle of app
hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_remote.txt

    mkdir logs
    python manage.py collectstatic
    rm -rf logs
  deploy:
    python manage.py migrate